name: Generate and Update Rulesets

on:
  schedule:
    - cron: '20 3 * * *'  # Run 03-20 am everyday.

permissions:
  contents: write

jobs:
  generate-rulesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      # - name: Install Dependencies
      #   run: |
      #     sudo apt update
      #     sudo apt install -y curl wget git jq

      # - name: Download latest release of generate-geoip-geosite
      #   run: |
      #     LINK2RELEASE=$(curl -s https://api.github.com/repos/Dunamis4tw/generate-geoip-geosite/releases/latest | jq -r '.assets[] | select(.browser_download_url|test("linux-amd64.")) | .browser_download_url')
      #     wget "$LINK2RELEASE" -O generate-geoip-geosite.tar.gz
      #     tar -xzf generate-geoip-geosite.tar.gz && rm generate-geoip-geosite.tar.gz
      #     chmod +x generate-geoip-geosite

      - name: Prepare tools
        run: |
          tar -xzf bin/sing-box.tar.gz
          tar -xzf bin/generate-geoip-geosite.tar.gz
          chmod +x sing-box generate-geoip-geosite

      - name: Generate rulesets
        run: |
          ./generate-geoip-geosite -s sourceAdAway.json -i ./adaway -o ./adaway --gen-rule-set-srs
          for i in $(ls custom/*.json); do ./sing-box rule-set compile "$i" && echo "Generate ruleset for $i"; done;

      - name: Cleanup
        run: |
          rm -f sing-box generate-geoip-geosite

      - name: Get current date
        id: date
        run: |
          echo "DATE=$(TZ=Europe/Moscow date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: githubaction@githubaction.com
          message: 'Update Lists ${{ env.DATE }}'
          push: true
          add: .
          default_author: github_actor
          fetch: --tags --force
          pathspec_error_handling: ignore
          github_token: ${{ secrets.RULESET_TOKEN }}
