name: Generate and Update AdAway Lists

on:
  schedule:
    - cron: '37 7 * * 3'  # Every wednesday at 7-35 am

permissions:
  contents: write

jobs:
  generate_lists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Pull Changes
        run: git pull

      - name: Set up Node.js (if required)
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust if needed

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl wget git jq

      - name: Download latest release of generate-geoip-geosite
        run: |
          LINK2RELEASE=$(curl -s https://api.github.com/repos/Dunamis4tw/generate-geoip-geosite/releases/latest | jq -r '.assets[] | select(.browser_download_url|test("linux-amd64.")) | .browser_download_url')
          wget "$LINK2RELEASE" -O generate-geoip-geosite.tar.gz
          tar -xzf generate-geoip-geosite.tar.gz && rm generate-geoip-geosite.tar.gz
          chmod +x generate-geoip-geosite

      - name: Configure sources json 
        run: |
          cat << EOF > adaway.json
          [
          {
            "url": "https://schakal.ru/hosts/alive_hosts_mail_fb.txt",
            "contentType": "HostsFile",
            "category": "adaway_alive_hosts_mail_fb"
          },
          {
            "url": "https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.txt",
            "contentType": "HostsFile",
            "category": "adaway_d3hosts"
          }
          ]
          EOF
        
      - name: Generate AdAway ruleset
        run: |
          ./generate-geoip-geosite -s adaway.json -i ./adaway -o ./adaway --gen-rule-set-srs --gen-rule-set-json          

      - name: Copy .srs and jason files to repository directory
        run: |
          mv ./adaway/*.srs /home/runner/work/sb-rule-sets/
          mv ./adaway/*.json /home/runner/work/sb-rule-sets/
          
      - name: Get current date
        id: date
        run: |
          echo "DATE=$(TZ=Europe/Moscow date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: githubaction@githubaction.com
          message: 'Update Lists ${{ env.DATE }}'
          push: true
          cwd: /home/runner/work/sb-rule-sets/
          default_author: github_actor
          fetch: --tags --force
          pathspec_error_handling: ignore
          new_branch: custom-new-branch
          github_token: ${{ secrets.RULESET_TOKEN }}
